version: "3.7"
services:

  flask_api:
    container_name: flask_api
    env_file:
      - .env.docker
    build: .
    working_dir: /app/app
    command: python -m flask run -h 0.0.0.0
    ports:
      - 5000:5000

  # rabbit:
  #   hostname: rabbit
  #   image: "rabbitmq:3-management"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: admin
  #     RABBITMQ_DEFAULT_PASS:  admin
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8002:8001"

  pchub_scrapyrt:
    container_name: pchub_scrapyrt
    image: "scrapinghub/scrapyrt"
    working_dir: /app
    ports:
      - "9080:9080"
    volumes:
      - ./scrapers/pchub_scraper:/app

  shopee_scrapyrt:
    container_name: shopee_scrapyrt
    image: "scrapinghub/scrapyrt"
    working_dir: /app
    ports:
      - "9081:9081"
    volumes:
      - ./scrapers/shopee_scraper:/app

  celery_worker:
    container_name: celery_worker
    build: .
    env_file:
      - .env.docker
    working_dir: /app/celery_worker
    command: celery -A tasks worker --loglevel=info
    depends_on:
      # - rabbit
      - redis
      - flask_api
