version: "3.7"
services:

  web:
    container_name: web_api
    env_file:
      - .env.docker
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis
      - scrapyrt

  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8002:8001"

  scrapyrt:
    container_name: scrapyrt
    image: "scrapinghub/scrapyrt"
    working_dir: /app
    ports:
      - "9080:9080"
    volumes:
      - ./scrapers/scrapy_scraper:/app
