# This config file is where the generic shopify scraper gets the parameters
dynaquest:
  site_url: "https://dynaquestpc.com"
  supplier: 'Dynaquest'
  handles:
    GPU: "graphics-card"
  filename_prefix: "dynaquest"

easypc:
  site_url: "https://easypc.com.ph"
  supplier: 'EasyPC'
  handles:
    GPU: "graphic-card"
  filename_prefix: "easypc"

pcx:
  site_url: "https://pcx.com.ph/"
  supplier: 'PC Express'
  handles:
    GPU: "graphics-cards"
  filename_prefix: "pcx"