# Sample url: https://pchubonline.com/browse?product=all&br=true&ct=false&sort=default-asc&y[0]=GPU&y[1]=GPU
pchub:
# This is the category query from the url
  category:
    GPU: "GPU"
    CPU: "Processor"
    MOBO: "Motherboard"
    RAM: "RAM"
    SSD: "SSD"
    HDD: "HDD"
    PSU: "PSU"
    CASE: "Case"
    # TODO: Do a looping in COOLER category there are CPU+Cooler and Cooling category
    COOLER: "CPU+Cooler"  
  id_prefix: "PCHB"
