# Sample url: https://shopee.ph/search?facet=11021163&noCorrection=true&page=0&searchKeyword=pcworx&shop=89683872 
# This config file is for shopee scraper
selectors:
  main: 'div[role="main"]'
  total_page: 'span.shopee-mini-page-controller__total::text'
  get_hrefs: 'div.shopee-search-item-result__item'
  product:
    name: 'div._44qnta span::text'
    price: 'div.pqTWkA::text'
    brand: 'a.GvvZVe::text'
    stock: 'label.zquA4o.eqeCX7:contains("Stock") + div::text'
    image: 'img._7D4JtJ::attr(src)'


facets:
  CPU: "11021164"
  GPU: "11021163"
  CPU: "11021164"
  MOBO: "11021166"
  RAM: "11021165"
  SSD: "11021148"
  HDD: "11021150"
  # TODO: Need to add psu search keyword
  PSU: "11021191"
  # TODO: Need to add case search keyword
  CASE: "11021167"
  # TODO: Need to add cooler search keyword
  COOLER: "11021167"  

shops:
  pcworx:
    shop_id: "89683872"
    searchKeyword: "pcworx"
    supplier: "PCWorx"
    id_prefix: "WORX"
  itworld:
    shop_id: "89762129"
    searchKeyword: "itwitw"
    supplier: "ITWorld"
    id_prefix: "ITW"
