# Sample url: https://easypc.com.ph/collections/graphic-card/products.json
# This config file is where the generic shopify scraper gets the parameters
dynaquest:
  site_url: "https://dynaquestpc.com"
  vendor: 'Dynaquest'
  slug:
    GPU: "graphics-card"
    CPU: "processor"
    MOBO: "motherboard"
    RAM: "memory"
    # TODO: Add ssd-m-2 into SSD category
    SSD: "hard-drive-ssd"
    HDD: "desktop-3-5"
    PSU: "power-supply"
    CASE: "chassis"
    COOLER: "cooling-solutions"  
  filename_prefix: "dynaquest"
  id_prefix: "DYNA"

easypc:
  site_url: "https://easypc.com.ph"
  vendor: 'EasyPC'
  slug:
    CPU: "processor"
    GPU: "graphic-card"
    MOBO: "motherboard"
    RAM: "memory"
    SSD: "solid-state-drive"
    HDD: "hard-disk"
    PSU: "power-supply"
    CASE: "pc-case"
    # TODO: Add chasis-fan into COOLER category
    COOLER: "cpu-cooling"  
  filename_prefix: "easypc"
  id_prefix: "EASY"

pcx:
  site_url: "https://pcx.com.ph"
  vendor: 'PC Express'
  slug:
    CPU: "processors"
    GPU: "graphics-cards"
    MOBO: "motherboards"
    RAM: "memory-modules"
    # TODO: Filter SSD and HDD
    SSD: "internal-storages"
    HDD: "internal-storages"
    PSU: "power-supplies"
    CASE: "pc-tower-cases"
    COOLER: "cooling" 
  filename_prefix: "pcx"
  id_prefix: "PCEX"

datablitz:
  site_url: "https://ecommerce.datablitz.com.ph"
  vendor: 'Datablitz'
  # TODO: Optimize
  slug:
    CPU: "pc-mac"
    GPU: "pc-mac"
    MOBO: "pc-mac"
    RAM: "pc-mac"
    SSD: "pc-mac"
    HDD: "pc-mac"
    PSU: "pc-mac"
    CASE: "pc-mac"
    COOLER: "pc-mac"
# datablitz product sorting is based from tags
  tags:
    CPU: "processor"
    GPU: "graphics-card"
    MOBO: "motherboard"
    RAM: "Desktop RAM"
    SSD: "SSD"
    HDD: "HDD"
    PSU: "power-supply"
    CASE: "PC Case"
    COOLER: "cooling fan" 
  filename_prefix: "datablitz"
  id_prefix: "DBLZ"