# This config file is for shopee scraper
selectors:
  main: 'div[role="main"]'
  total_page: 'span.shopee-mini-page-controller__total::text'
  get_hrefs: 'div.shopee-search-item-result__item'
  product:
    name: 'div._44qnta span::text'
    price: 'div.pqTWkA::text'
    brand: 'a.GvvZVe::text'
    stock: 'label.zquA4o.eqeCX7:contains("Stock") + div::text'
    image: 'img._7D4JtJ::attr(src)'


facets:
  CPU: "11021164"
  GPU: "11021163"

shops:
  pcworx:
    shop_id: "89683872"
    searchKeyword: "pcworx"
    supplier: "PCWorx"
    id_prefix: "WORX"