# This config file is for shopee scraper
selectors:
  main: 'div[role="main"]'
  total_page: 'span.shopee-mini-page-controller__total::text'
  get_hrefs: 'div.shopee-search-item-result__item'
  product:
    name: 'div._44qnta span::text'
    price: 'div.pqTWkA::text'
    brand: 'a.GvvZVe::text'


facets:
  GPU: "11021163"

shops:
  pcworx:
    shop_id: "89683872"
    searchKeyword: "pcworx"
    supplier: "PCWorx"